# Generated by Django 6.0.3 on 2026-03-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('visitas', models.IntegerField(default=0)),
                ('pedidos', models.IntegerField(default=0)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
